# -*- coding: utf-8 -*-

from . import models
from . import hr_employee_inherit
from . import conjoint
from . import hr_contrat_inherit
from . import fin_relation
from . import type_fin_relation
from . import visite_medicale
from . import enfant
from . import cabinet_medical
from . import visite_medical_line
from . import formation
from . import type_formation
from . import formation_line
from . import organisme
from . import sanction
from . import absence
from . import type_faute
from . import type_file
from . import type_absence
from . import type_conge
from . import type_sanction
from . import accident_travail
from . import absence_formation
from . import commission_line
from . import hr_holidays_inherit
from . import file
from . import conge_droit
from . import conge_droit_month
from . import grille
from . import categorie
from . import categorie_superieure
from . import echelon
from . import niveau_hierarchique
from . import niveau_hierarchique_chef_bureau
from . import section
from . import section_superieure
from . import groupe
from . import hr_job_inherit
from . import loi
from . import filiere
from . import corps
from . import grade
from . import promotion
from . import avancement
from . import promotion_ligne
from . import avancement_ligne
from . import type_fonction
from . import avencement_droit
from . import promotion_droit
from . import avancement_commission_line
from . import promotion_commission_line
from . import company
from . import emphy
from . import planning_surveillance
from . import planning_surveillance_line
from . import fiche_evaluation
from . import hr_contract_type_inherit


